from pydantic import BaseModel, Field
from typing import List

# 1. Schema for the Recipe Agent's final output
class RecipeStep(BaseModel):
    """A single, clear instruction step for the Sous Chef."""
    step_number: int = Field(description="The sequential number of the cooking step.")
    instruction: str = Field(description="The detailed instruction for this step (e.g., 'Chop the onions finely').")
    duration_minutes: int = Field(description="The approximate time in minutes for this step.")

class RecipeOutput(BaseModel):
    """The complete structured recipe generated by the Recipe Agent."""
    meal_name: str = Field(description="The suggested name for the final dish.")
    ingredients_list: List[str] = Field(description="A list of all ingredients and quantities required.")
    instructions: List[RecipeStep] = Field(description="The step-by-step cooking instructions.")
    # The Manager Agent is interested in the instructions list to feed the Sous Chef!

# 2. Schema for the Sous Chef Tool's Input (The Manager calls the Sous Chef with this)
class SousChefInput(BaseModel):
    step_instruction: str = Field(description="The single, current instruction text the user needs guidance on.")
    step_duration: int = Field(description="The estimated time in minutes for the user to complete this step.")

# 3. Dummy Schema for Manager's Initial Input (Used to extract ingredients from the user's free text)
class InitialInput(BaseModel):
    """Model for extracting key ingredients from the user's initial prompt."""
    key_ingredients: List[str] = Field(description="A list of 3-5 main ingredients provided by the user.")
